const translations = {
  en: {
    heroSubtitle: "<strong>We’ve made advanced badminton analysis accessible to everyone.</strong> By letting a coach or teammate tag your play during a tournament, every rally becomes valuable data. Discover your hidden patterns, adjust your tactics, and take your game to the next level.",
    linkAnalysis: "See what an analysis looks like",
    linkPreview: "View Store preview",
    faqLink: "Frequently Asked Questions",
    aboutTitle: "About the app",
    aboutText: "Record your badminton match live and receive analysis as soon as the match ends—or even during the break between games.",
    howTitle: "How it works",
    step1Title: "Hand over your device",
    step1Text: "Give your phone or Android tablet to your coach, teammate, or friend so they can operate the app while you focus on playing.",
    step2Title: "Record the match",
    step2Text: "Your assistant can track the end of each rally by recording the serve, the location of the final shot, where it landed, the outcome, and the shot type.",
    step3Title: "Get instant analysis",
    step3Text: "As soon as the match is over, or during a break between games, you will see a complete breakdown of how you won and lost points.",
    patternsTitle: "Winning patterns and tactics",
    patternsText1: "Which of your shots—smash, net play, drop shot, or something else—is winning you the most points today?",
    patternsText2: "Can you use them more effectively?",
    patternsText3: "Where do they win most of their points?",
    patternsText4: "How can you respond better?",
    discoverTitle: "Discover your patterns",
    mistakesTitle: "Your mistakes",
    mistakesText1: "Do you make more unforced errors at the beginning or end of games?",
    mistakesText2: "Which shot types cause the most problems?",
    mistakesText3: "Can you use more margins to make them good?",
    opponentTitle: "Opponent's mistakes",
    opponentText: "Do they make more mistakes from specific court positions or in longer rallies?",
    analysisTitle: "Match analysis",
    analysisIntro: "At any point during the match, between games, or afterward, you can view detailed statistics, including:",
    analysisItem1: "Heat maps",
    analysisItem2: "Shot type statistics",
    analysisItem3: "Rally length statistics",
    analysisItem4: "Every rally played during the match",
    detailedAnalysis: "Detailed rally analysis",
    detailedAnalysisText: "lets you open any rally and see exactly how it unfolded shot by shot.",
    shareAnalysis: "Share your analysis",
    shareAnalysisText: "using your device's Share function to export it as a BmMatch file or as an HTML report that can be shared with coaches or teammates.",
    appPreviewLink: "App preview",
    privacyLink: "Privacy policy",
    homeLink: "Home",
    appCategory: "Sports · Training",
    appSubtitle: "Professional badminton match analyzer for coaches, clubs, and competitive players.",
    metaLocalRecords: "Local match records",
    metaOffline: "Offline-ready app",
    badgeSupports: "Supports .BmMatch files",
    badgePersistence: "Automatic local persistence",
    appDescription: "Open, track, and review of badminton match records with BWF-standard scoring, automatic recovery, and robust rally-level analysis. Export results and continue matches on any compatible device.",
    offeredBy: "Download",
    downloadApk: "app-release.apk",
    tagInstallable: "Installable Android app",
    tagOffline: "Works offline",
    previewWarning: "Preview version: This app is not yet available on Google Play. Download the APK only from this official GitHub page. Please read the Privacy Policy above for more information about what the app does.",
    screenshotMatchSetup: "Match setup",
    screenshotQuickStart: "Quick start guide",
    screenshotRecordingHelp: "Recording rally help",
    screenshotToss: "Toss",
    screenshotServe: "Serve",
    screenshotServeAfter: "Serve after rally",
    screenshotResume: "Resume",
    screenshotAnalysis1: "Analysis 1",
    screenshotAnalysis2: "Analysis 2",
    screenshotAnalysis3: "Analysis 3",
    screenshotReplay: "Analysis replay",
    aboutAppTitle: "About this app",
    aboutAppText: "Badminton Match Coach is a professional badminton match analyzer built for real matches and post-game review. It supports BWF-standard scoring, .BmMatch match records, and automatic local persistence so sessions are recovered after refresh or reload.",
    featureFastScoring: "Fast scoring",
    featureFastScoringText: "Tap each rally serve and end with, final shot, and outcome details to capture the full match flow.",
    featureBwfRules: "BWF rules",
    featureBwfRulesText: "Tracks games to 15 with a 2-point margin, max 21, and standard match progression for singles and doubles.",
    featureMatchRecovery: "Match recovery",
    featureMatchRecoveryText: "Automatic local storage sync preserves your session and allows seamless resume after reopening the app.",
    featureMatchRecoveryNote: "Don't forget to update games, score and server information (see Resume screen above).",
    howItWorksTitle: "How it works",
    stepStartMatch: "Start a new match",
    stepStartMatchText: "— use new match to open a session instantly.",
    stepTrackRallies: "Track every rally",
    stepTrackRalliesText: "— log shots, outcomes, and service position in real time.",
    stepSaveFiles: "Open or save .BmMatch files",
    stepSaveFilesText: "— load saved match recordings or export the analysis for later review.",
    analysisTitlePlay: "Match analysis",
    analysisTextPlay: "Analyze every match with built-in post-game summaries, rally histories, and export-ready reports. The app is designed to help you review performance and improve strategy at every level.",
    heatMapsTitle: "Heat maps",
    heatMapsText: "See where points were won and lost on the court for better tactical planning.",
    shotStatsTitle: "Shot statistics",
    shotStatsText: "Measure smash accuracy, net play success, drop shots, clears, and more.",
    rallyTimelineTitle: "Rally timeline",
    rallyTimelineText: "Open any rally and review how the point developed shot by shot.",
    fileHandlingTitle: "File handling",
    fileHandlingText: "Load and save .BmMatch files to preserve match analysis and collaborate with coaches and teammates.",
    systemRequirementsTitle: "System requirements",
    systemRequirementsText: "Badminton Match Coach is a standalone Android app built for real match recording and analysis.",
    requirementAndroid: "Android 5.0 (API level 21) or higher",
    requirementApi: "Target API level 33",
    requirementBmMatch: "Supports opening and handling <strong>.BmMatch</strong> match files via Android file and content intents",
    requirementShortcut: "Includes a quick \"New Match\" shortcut for fast match setup",
    requirementPermissions: "Requires standard Android app permissions only; it runs natively on Android as a standalone app",
    versionLabel: "Version",
    updatedLabel: "Updated",
    updatedValue: "July 2026",
    contactLabel: "Contact",
    analysisPageTitle: "Analysis",
    analysisPageSubtitle: "See how match patterns become clear when you review a match in detail.",
    analysisWhyTitle: "Why this matters",
    analysisWhyText: "Ever wondered why you keep losing to the same player? A detailed breakdown can reveal the patterns behind those results.",
    analysisExampleTitle: "Example Analysis",
    analysisExampleText: "Here is an example of a match between the Olympic Champion and the reigning World Champion. The same type of analysis is available in the app during and after a match.",
    analysisLinkMen: "Open Men's single match analysis",
    analysisDoublesIntro: "Below is an example of how a doubles match analysis is displayed.",
    analysisLinkMixed: "Open Mixed match analysis",
    analysisLearnTitle: "What you can learn",
    analysisLearnItem1: "Which patterns repeat most often",
    analysisLearnItem2: "Where your points are won and lost",
    analysisLearnItem3: "How tactical choices change the flow of a match",
    analysisBackHome: "Back to home",
    privacyTitle: "Privacy Policy",
    privacyIntro: "Badminton Match Coach respects your privacy. This policy explains what data the Android app collects, how it is stored, and how it is used.",
    dataCollectedTitle: "Data collected",
    dataCollectedItem1: "Match event details entered by users, including rally outcomes, shot types, and scoring events — kept in the app's runtime memory by default.",
    dataCollectedItem2: "Match metadata such as player names, competition details, and session timestamps — kept in the app's runtime memory by default.",
    dataCollectedItem3: "Local session state used to recover match progress while the app is running.",
    dataCollectedItem4: "Optional .BmMatch files opened or exported by the user. When you choose to save or export a match file, it is written to the device where the app is running (by default to the Documents/Badminton folder) and not uploaded or shared automatically.",
    dataUseTitle: "How data is used",
    dataUseText: "Match data is used only to provide analysis, scoring, undo/redo history, and report generation. Data remains local unless you choose to export a .BmMatch file or share a report.",
    storageTitle: "Storage and offline use",
    storageText: "The app keeps match data in its runtime memory while you use it. If you explicitly save or export a match (for example to a <strong>.BmMatch</strong> file), the file is written to the device's storage — by default we place exported files in the <strong>Documents/Badminton</strong> folder on the device where the app is running. The app operates fully offline and does not upload data unless you manually share or export a file.",
    permissionsTitle: "Permissions",
    permissionsText: "No location, camera, or personal account permissions are required. The app only requests storage access when saving or opening a match file."
  },
  sv: {
    heroSubtitle: "<strong>Vi har gjort avancerad badmintonanalys tillgänglig för alla.</strong> Genom att låta någon runt banan tagga ditt spel i appen förvandlas varje duell till värdefull data. Upptäck dina dolda mönster, träna på rätt saker och lyft ditt spel till nästa nivå.",
    linkAnalysis: "Se hur analysen ser ut",
    linkPreview: "Visa förhandsvisning Store",
    faqLink: "Vanliga frågor",
    aboutTitle: "Om appen",
    aboutText: "Spela in din badmintonmatch live och få analys så snart matchen är slut – eller till och med under pausen mellan set.",
    howTitle: "Så fungerar det",
    step1Title: "Lämna över din enhet",
    step1Text: "Ge din telefon eller Android-platta till din tränare, lagkamrat eller vän så att de kan styra appen medan du fokuserar på att spela.",
    step2Title: "Spela in matchen",
    step2Text: "Din assistent kan klicka serv, retur och klicka hur varje rally slutar, var den sista bollen slogs ifrån, var den landade, resultatet och typ av slag.",
    step3Title: "Få omedelbar analys",
    step3Text: "Så snart matchen är över, eller under en paus mellan set, ser du en komplett uppdelning av hur du vann och förlorade poäng.",
    patternsTitle: "Vinnande mönster och taktik",
    patternsText1: "Vilket av dina slag – smash, nätspel, drop eller något annat – ger dig flest poäng idag?",
    patternsText2: "Kan du använda dem mer effektivt?",
    patternsText3: "Var vinns de flesta av dina poäng?",
    patternsText4: "Hur kan du göra det bättre?",
    discoverTitle: "Upptäck dina mönster",
    mistakesTitle: "Dina misstag",
    mistakesText1: "Gör du fler ofrivilliga fel i början eller slutet av ett set?",
    mistakesText2: "Vilka slag skapar flest problem?",
    mistakesText3: "Kan du använda mer marginal vid dessa slag?",
    opponentTitle: "Motståndarens misstag",
    opponentText: "Gör de fler misstag från specifika positioner på banan eller i längre rallyn?",
    analysisTitle: "Matchanalys",
    analysisIntro: "När som helst under matchen, mellan set eller efteråt kan du visa detaljerad statistik, inklusive:",
    analysisItem1: "Heatmaps",
    analysisItem2: "Statistik över slagtyp",
    analysisItem3: "Statistik över rallylängd",
    analysisItem4: "Varje rally som spelades under matchen",
    detailedAnalysis: "Detaljerad rallyanalys",
    detailedAnalysisText: "låter dig öppna vilket rally som helst och se exakt hur den spelades slag för slag.",
    shareAnalysis: "Dela din analys",
    shareAnalysisText: "med hjälp av enhetens Dela-funktion för att exportera den som en BmMatch-fil eller som en HTML-rapport som kan delas med tränare eller lagkamrater.",
    appPreviewLink: "Appförhandsvisning",
    privacyLink: "Integritetspolicy",
    homeLink: "Hem",
    appCategory: "Sport · Träning",
    appSubtitle: "Professionell badmintonmatchanalys för tränare, klubbar och tävlingsspelare.",
    metaLocalRecords: "Lokalt match register",
    metaOffline: "App som fungerar offline",
    badgeSupports: "Stödjer .BmMatch-filer",
    badgePersistence: "Sparar automatisk",
    appDescription: "Öppna, registrera och granska badmintonmatcher med BWF-standardiserad poängräkning, sparar löpande och återställer automatiskt vid problem, alltid robust analys på rallynivå. Exportera resultat och fortsätt matcher på vilken kompatibel enhet som helst.",
    offeredBy: "Ladda ner",
    downloadApk: "app-release.apk",
    tagInstallable: "Installerbar android app",
    tagOffline: "Fungerar offline",
    previewWarning: "Förhandsversion: Appen finns inte på Google Play ännu. Ladda endast ner APK-filen från denna officiella GitHub-sida. Läs gärna Integritetspolicy ovan för mer information om vad appen gör.",
    screenshotMatchSetup: "Matchinställning",
    screenshotQuickStart: "Snabbstartsguide",
    screenshotRecordingHelp: "Hjälp för att spela in rally",
    screenshotToss: "Slagning",
    screenshotServe: "Serve",
    screenshotServeAfter: "Serve efter rally",
    screenshotResume: "Återuppta",
    screenshotAnalysis1: "Analys 1",
    screenshotAnalysis2: "Analys 2",
    screenshotAnalysis3: "Analys 3",
    screenshotReplay: "Rally uppspelning",
    aboutAppTitle: "Om appen",
    aboutAppText: "Badminton Match Coach är en professionell badmintonmatchanalysator byggd för riktiga matcher och analys under och efter matchen. Den stöder BWF-standardiserad poängräkning, .BmMatch-register och automatisk lokalt sparande så att sessioner återställs efter uppdatering eller omstart.",
    featureFastScoring: "Snabb poängräkning",
    featureFastScoringText: "Tryck på varje rallys serve och slut bollar samt detaljer om sista skott, resultat och utfall för att fånga hela matchflödet.",
    featureBwfRules: "BWF-regler",
    featureBwfRulesText: "Spårar set till 15 med två poängs marginal, max 21 och standardiserade matchregler för singel och dubbel.",
    featureMatchRecovery: "Återupptag av match",
    featureMatchRecoveryText: "Automatisk lokal lagring bevarar sessionen och gör det enkelt att återuppta efter att appen stängs ner och öppnas igen.",
    featureMatchRecoveryNote: "Glöm inte att uppdatera set, poäng och serverinformation (se skärmen Återuppta ovan).",
    howItWorksTitle: "Så fungerar det",
    stepStartMatch: "Starta en ny match",
    stepStartMatchText: "— registrera enkelt en ny match för att starta matchen.",
    stepTrackRallies: "Spåra varje rally",
    stepTrackRalliesText: "— logga skott, utfall och serveposition i realtid.",
    stepSaveFiles: "Öppna eller spara .BmMatch-filer",
    stepSaveFilesText: "— ladda sparade matchinspelningar eller exportera analysen för senare granskning.",
    analysisTitlePlay: "Matchanalys",
    analysisTextPlay: "Analysera varje match med inbyggda sammanfattningar efter matchen, rallyhistorik och exportklara rapporter. Appen är utformad för att hjälpa dig granska prestation och förbättra strategin på alla nivåer.",
    heatMapsTitle: "Heatmaps",
    heatMapsText: "Se var poäng vanns eller förlorades på banan för bättre taktisk planering.",
    shotStatsTitle: "Slagstatistik",
    shotStatsText: "Mät smashnoggrannhet, nätspelsframgång, drop shots, clears och mycket mer.",
    rallyTimelineTitle: "Rallytidslinje",
    rallyTimelineText: "Öppna vilket rally som helst och granska hur poängen utvecklades slag för slag och position på banan.",
    fileHandlingTitle: "Filhantering",
    fileHandlingText: "Ladda och spara .BmMatch-filer för att bevara matchanalys och samarbeta med tränare och lagkamrater. Dina filer sparas i Documents/Badminton foldern.",
    systemRequirementsTitle: "Systemkrav",
    systemRequirementsText: "Badminton Match Coach är en fristående Android-app byggd för att spela in och analysera riktiga matcher.",
    requirementAndroid: "Android 5.0 (API-nivå 21) eller högre",
    requirementApi: "Mål-API-nivå 33",
    requirementBmMatch: "Stöder öppnande och hantering av <strong>.BmMatch</strong>-matchfiler via Androids fil- och innehållsdelning",
    requirementShortcut: "Inkluderar en snabb \"Ny match\"-genväg för snabb matchinställning",
    requirementPermissions: "Kräver endast standard Android-appbehörigheter; den körs som en fristående app på Android",
    versionLabel: "Version",
    updatedLabel: "Uppdaterad",
    updatedValue: "Juli 2026",
    contactLabel: "Kontakt",
    analysisPageTitle: "Analys",
    analysisPageSubtitle: "Se hur matchmönster blir tydliga när du går igenom en match i detalj.",
    analysisWhyTitle: "Varför detta spelar roll",
    analysisWhyText: "Har du undrat varför du ständigt förlorar mot samma spelare? En detaljerad uppdelning kan avslöja mönstren bakom resultaten.",
    analysisExampleTitle: "Exempelanalys",
    analysisExampleText: "Här är ett exempel på en match mellan OS-mästaren och den sittande världsmästaren. Samma typ av analys finns i appen under och efter en match.",
    analysisLinkMen: "Öppna analys för herrsingel",
    analysisDoublesIntro: "Nedan visas ett exempel på hur en dubbelanalys presenteras.",
    analysisLinkMixed: "Öppna analys för mixed",
    analysisLearnTitle: "Vad du kan lära dig",
    analysisLearnItem1: "Vilka mönster upprepas oftast",
    analysisLearnItem2: "Var dina poäng vinns och förloras",
    analysisLearnItem3: "Hur taktiska val förändrar matchens flöde",
    analysisBackHome: "Tillbaka till startsidan",
    privacyTitle: "Integritetspolicy",
    privacyIntro: "Badminton Match Coach respekterar din integritet. Den här policyn förklarar vilka uppgifter Android-appen samlar in, hur de lagras och hur de används.",
    dataCollectedTitle: "Insamlade uppgifter",
    dataCollectedItem1: "Matchhändelser som användare matar in, inklusive rallyutfall, slagtyper och poänghändelser — lagras i appens minne som standard.",
    dataCollectedItem2: "Matchmetadata såsom spelarnamn, tävlingsuppgifter och sessionstidsstämplar — lagras i appens minne som standard.",
    dataCollectedItem3: "Lokal sessionstillstånd som används för att återställa matchförlopp medan appen körs.",
    dataCollectedItem4: "Valfria .BmMatch-filer som öppnas eller exporteras av användaren. När du väljer att spara eller exportera en matchfil skrivs den till den enhet där appen körs (som standard till Documents/Badminton) och laddas inte upp eller delas automatiskt.",
    dataUseTitle: "Hur uppgifterna används",
    dataUseText: "Matchdata används endast för att tillhandahålla analys, poängräkning, ångra/göra om-historik och rapportgenerering. Data förblir lokalt om du inte väljer att exportera en .BmMatch-fil eller dela en rapport.",
    storageTitle: "Lagring och offlineanvändning",
    storageText: "Appen lagrar matchdata i minnet medan du använder den. Om du uttryckligen sparar eller exporterar en match (till exempel till en <strong>.BmMatch</strong>-fil) skrivs filen till enhetens lagring — som standard placerar vi exporterade filer i <strong>Documents/Badminton</strong> på den enhet där appen körs. Appen fungerar helt offline och laddar inte upp data om du inte manuellt delar eller exporterar en fil.",
    permissionsTitle: "Behörigheter",
    permissionsText: "Inga behörigheter för plats, kamera eller personliga konton krävs. Appen begär endast lagringsåtkomst när en matchfil sparas eller öppnas."
  }
};

function applyLanguage(lang) {
  const selected = translations[lang] || translations.en;
  document.documentElement.lang = lang;

  document.querySelectorAll('[data-i18n]').forEach((element) => {
    const key = element.getAttribute('data-i18n');

    if (selected[key]) {
      element.innerHTML = selected[key];
    }
  });

  document.querySelectorAll('.lang-btn').forEach((button) => {
    const isActive = button.getAttribute('data-lang') === lang;
    button.classList.toggle('active', isActive);
    button.setAttribute('aria-pressed', isActive ? 'true' : 'false');
  });

  localStorage.setItem('preferred-language', lang);
}

document.addEventListener('DOMContentLoaded', () => {
  const storedLanguage = localStorage.getItem('preferred-language');
  const initialLanguage = storedLanguage === 'sv' ? 'sv' : 'en';

  applyLanguage(initialLanguage);

  document.querySelectorAll('.lang-btn').forEach((button) => {
    button.addEventListener('click', () => applyLanguage(button.getAttribute('data-lang')));
  });
});